### PR TITLE
Added functionality to collapse player widgets

### PR DESCRIPTION
**Pull request by mank319**
With multiple players open the panel can become a bit cluttered. Therefore I made the widgets collapsible.

### CODE REVIEW

**Comment by mank319** [comment]
I added a little "screencast" demonstrating the new feature:
collapse2

**Comment by ikeydoherty** [comment]
Looks fine to me, cheers!

**Comment by ikeydoherty** [comment]
Gonna remove the focus on those, bugging me :P

**Comment by mank319** [comment]
@ikeydoherty I agree. That shouldn't be the default UI element with focus on it.

**Pull request merged**
